spring:
  application:
    name: spring-cloud-eureka

  security:
    user:
      name: eureka         # 配置登录的账号是 eureka
      password: 123456     # 配置登录的密码是 123456

server:
  port: 8001

eureka:
  server:
    # 分别是关闭自我保护
    enable-self-preservation: false
    # 清理间隔 实际开发过程中，我们可能会不停地重启服务，由于Eureka有自己的保护机制，故节点下线后，服务信息还会一直存在于Eureka中。
    # 我们可以通过增加一些配置让移除的速度更快一点，当然只在开发环境下使用，生产环境下不推荐使用
    eviction-interval-timer-in-ms: 5000

  instance:
    # eureka client向eureka server发送心跳的时间间隔，默认30秒，将此值改小可解决eureka注册慢的问题
    lease-renewal-interval-in-seconds: 5
    # 续约到期时间（默认90秒）
    lease-expiration-duration-in-seconds: 5
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8002/eureka/

    # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例, 并不需要检索服务, 所以也设置为 false
    fetch-registry: false