server:
  port: 8001

spring:
  application:
    name: xwder-eureka-01

eureka:
  instance:
    hostname: xwder-eureka-01
  server:
    # 关闭自我保护模式（当一定时间内没有收到某个微服务实例的心跳时，不会注销这个微服务）
    enable-self-preservation: false
    # 清理时间间隔（单位毫秒，默认60*1000
    eviction-interval-timer-in-ms: 3000
  client:
    #    eureka服务器访问地址
    service-url:
      defaultZone: http://xwder-eureka-02:8002/eureka,http://xwder-eureka-03:8003/eureka
    #    是否需要检索服务（检索服务是client端的事）
    fetch-registry: false
    #    是否向注册中心注册自己（因为它就是注册中心，负载均衡时需要用到）
    register-with-eureka: false
