server:
  port: 8001

spring:
  application:
    name: spring-cloud-eureka

eureka:
  instance:
    hostname: xwder-eureka-01
  server:
    # 关闭自我保护模式（当一定时间内没有收到某个微服务实例的心跳时，不会注销这个微服务）
    enable-self-preservation: false
    # 清理时间间隔（单位毫秒，默认60*1000
    eviction-interval-timer-in-ms: 3000
  client:
    #    eureka服务器访问地址
    service-url:
      defaultZone: http://xwder-eureka-02:8002/eureka/,http://xwder-eureka-03:8003/eureka/
