# 开发环境配置
server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:

  devtools:
    restart:
      enabled: true

  # 模板引擎
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    # 禁用缓存
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# 日志配置
logging:
  level:
    com.dimple: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug