spring:
  profiles:
    active: dev



# 项目相关配置
xwder-manage:
  # 名称
  name: DimpleBlog
  # 版本
  version: 1.1
  # 版权年份
  copyrightYear: 2019
  # 文件路径
  profile: D:/profile/
  # 获取ip地址开关
  addressEnabled: true
  #七牛云配置
  qiniuyun:
    accessKey: i_IPvlaEUGxJmc2u9935JCWQZoOGfp62kS41LHtP
    secretKey: b-WSHXOfbPJtfGO0cLtFFtYtPWR3Jx2xds6d4WAt
    bucket: xwder
    path: https://pic.xwder.com
    imageMaxSize: 52428800
    imageMaxNameLength: 200
