# 开发环境配置
server:
  # 服务端口
  port: 8080
  servlet:
    # 项目contextPath
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

spring:
  devtools:
    restart:
      enabled: true
  # 模板引擎
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    # 禁用缓存
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: xwder-manage

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://eureka:123456@xwder-eureka-01:8001/eureka/,http://eureka:123456@xwder-eureka-02:8002/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:  # 服务名，default表示所有服务
        connectTimeout: 10000
        readTimeout: 60000
        loggerLevel: full  # full | basic | none | headers
        #requestInterceptors: 拦截器
      XWDER-PROVIDER-CQUST:
        loggerLevel: full

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000


# 日志配置
logging:
  level:
    com.xwder: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug
    com.xwder.api.book.BookInfoServiceApi: debug


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
      # 暴露.端点
        include: '*'
      # 取消暴露metrics端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        #exclude: '*'